name: SimpleKiosk
on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate datetime tag
        id: tag
        run: |
          TAG="$(date -u +'%Y%m%d')"
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: 'thecuriousgeek/simplekiosk'
          token: ${{ secrets.GH_PAT }}
          path: 'builder'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache-dependency-path: builder/app/build.gradle
          cache: gradle

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: wrapper

      - name: Build with Gradle
        working-directory: ./builder
        run: ./gradlew assembleDebug

      - name: Create Local Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          files: builder/app/build/outputs/apk/debug/*.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}